trigger:
- {{ branch }}

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ./configure
- script: make
  displayName: Compile the Code
- name: test in dir
  script: pwd; echo *
  workingDirectory: ./dir