jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: echo ./configure
    - name: make
      run: echo make
    - name: make check
      run: echo make check
    - name: make distcheck
      run: echo make distcheck