name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Test Multiline String
      run: |
        ls
        pwd
    - name: Clean temp directory
      run: echo rm -rf abc
      working-directory: ./temp
