name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: Test Multiline String
      run: |
        ls
        pwd
    - name: test in dir
      run: pwd; echo *
      working-directory: ./dir
    - run: pwd
    - name: Display the path
      run: echo ${env:PATH}
      shell: powershell

    - name: Display the path
      run: |
        import os
        print(os.environ['PATH'])
      shell: python